apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-eks-fargate-cluster
  region: us-west-1

fargateProfiles:
  - name: fargate
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: staging
    selectors:
      - namespace: staging
        labels:
          env: staging
          checks: passed
